"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { InfoIcon } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@crm-fran/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@crm-fran/ui/components/card";
import { Empty } from "@crm-fran/ui/components/empty";
import { Field, FieldGroup, FieldLabel } from "@crm-fran/ui/components/field";
import { Input } from "@crm-fran/ui/components/input";
import { Popover, PopoverContent, PopoverDescription, PopoverHeader, PopoverTitle, PopoverTrigger } from "@crm-fran/ui/components/popover";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@crm-fran/ui/components/select";
import { Skeleton } from "@crm-fran/ui/components/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@crm-fran/ui/components/table";
import { trpc } from "@/utils/trpc";
const kinds = [{ value: "contracted_sale", label: "Venta contratada" }, { value: "discount", label: "Descuento" }, { value: "payment_received", label: "Cobro recibido" }, { value: "refund", label: "Reembolso" }, { value: "chargeback", label: "Contracargo" }, { value: "commission", label: "Comisión" }, { value: "cost", label: "Coste directo" }] as const;
const money = (cents: number, currency: string) => new Intl.NumberFormat("es-ES", { style: "currency", currency }).format(cents / 100);
export function FinancialTruthSection() {
  const client = useQueryClient(); const [search, setSearch] = useState(""); const [leadId, setLeadId] = useState(""); const [kind, setKind] = useState<typeof kinds[number]["value"]>("payment_received"); const [amount, setAmount] = useState(""); const [currency, setCurrency] = useState("EUR"); const [occurredAt, setOccurredAt] = useState("");
  const leads = useQuery(trpc.profitability.attributionLeads.queryOptions({ query: search, limit: 50 })); const ledger = useQuery({ ...trpc.profitability.listFinancialLedger.queryOptions({ leadId }), enabled: Boolean(leadId) }); const refresh = () => client.invalidateQueries(trpc.profitability.listFinancialLedger.queryFilter());
  const record = useMutation(trpc.profitability.recordFinancialEvent.mutationOptions({ onSuccess: async () => { toast.success("Hecho financiero registrado"); setAmount(""); await refresh(); }, onError: (error) => toast.error(error.message) })); const reverse = useMutation(trpc.profitability.reverseFinancialEvent.mutationOptions({ onSuccess: async () => { toast.success("Reversión auditada registrada"); await refresh(); }, onError: (error) => toast.error(error.message) }));
  const submit = () => { const amountCents = Math.round(Number(amount) * 100); if (leadId && amountCents > 0 && occurredAt) record.mutate({ leadId, kind, amountCents, currency, occurredAt: new Date(occurredAt).toISOString(), idempotencyKey: crypto.randomUUID() }); };
  return <div className="flex flex-col gap-4"><Card><CardHeader><div className="flex items-center gap-1"><CardTitle>Verdad económica</CardTitle><Popover><PopoverTrigger render={<Button variant="ghost" size="icon-xs" aria-label="Información sobre verdad económica" />}><InfoIcon aria-hidden="true" /></PopoverTrigger><PopoverContent><PopoverHeader><PopoverTitle>Ledger financiero real</PopoverTitle><PopoverDescription>Hechos manuales separados de estimaciones. Cada moneda se proyecta por separado y una corrección añade una reversión auditable.</PopoverDescription></PopoverHeader></PopoverContent></Popover></div><CardDescription>Cobrado, pendiente, reembolsos, costes y margen basados únicamente en eventos reales.</CardDescription></CardHeader></Card>
  <Card><CardHeader><CardTitle>Seleccionar lead</CardTitle></CardHeader><CardContent><FieldGroup><Field><FieldLabel htmlFor="truth-search">Buscar lead</FieldLabel><Input id="truth-search" value={search} onChange={(event) => { setSearch(event.target.value); setLeadId(""); }} /></Field>{leads.isPending ? <Skeleton className="h-9 w-full" /> : leads.isError ? <p className="text-sm text-destructive">No se pudieron cargar los leads.</p> : <Field><FieldLabel>Lead</FieldLabel><Select value={leadId || null} onValueChange={(value) => setLeadId(value ?? "")}><SelectTrigger aria-label="Lead para verdad económica"><SelectValue placeholder="Selecciona un lead" /></SelectTrigger><SelectContent><SelectGroup>{(leads.data ?? []).map((lead) => <SelectItem key={lead.id} value={lead.id}>{lead.name} · {lead.email}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>}</FieldGroup></CardContent></Card>
  {leadId && <><Card><CardHeader><CardTitle>Proyección real por moneda</CardTitle><CardDescription>Las monedas nunca se mezclan.</CardDescription></CardHeader><CardContent>{ledger.isPending ? <Skeleton className="h-32 w-full" /> : ledger.isError ? <p className="text-sm text-destructive">No se pudo cargar el ledger.</p> : !ledger.data?.projectionByCurrency.length ? <Empty heading="Sin hechos financieros" description="Registra el primer hecho real." /> : <Table><TableHeader><TableRow><TableHead>Moneda</TableHead><TableHead>Contratado</TableHead><TableHead>Cobrado</TableHead><TableHead>Pendiente</TableHead><TableHead>Reembolsos</TableHead><TableHead>Costes</TableHead><TableHead>Margen</TableHead></TableRow></TableHeader><TableBody>{ledger.data.projectionByCurrency.map((row) => <TableRow key={row.currency}><TableCell>{row.currency}</TableCell><TableCell>{money(row.netContractedCents,row.currency)}</TableCell><TableCell>{money(row.realizedCashCents,row.currency)}</TableCell><TableCell>{money(row.outstandingContractedBalanceCents,row.currency)}</TableCell><TableCell>{money(row.refundsAndChargebacksCents,row.currency)}</TableCell><TableCell>{money(row.commissionsCents+row.directCostsCents,row.currency)}</TableCell><TableCell>{money(row.realizedMarginBeforeAdsCents,row.currency)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
  <Card><CardHeader><CardTitle>Registrar hecho real</CardTitle><CardDescription>Solo administración; ningún importe se infiere.</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel>Tipo</FieldLabel><Select value={kind} onValueChange={(value) => { if (kinds.some((item) => item.value === value)) setKind(value as typeof kind); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{kinds.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="truth-amount">Importe</FieldLabel><Input id="truth-amount" type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></Field><Field><FieldLabel htmlFor="truth-currency">Moneda ISO</FieldLabel><Input id="truth-currency" maxLength={3} value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} /></Field><Field><FieldLabel htmlFor="truth-date">Fecha y hora</FieldLabel><Input id="truth-date" type="datetime-local" value={occurredAt} onChange={(event) => setOccurredAt(event.target.value)} /></Field><Button disabled={record.isPending || !amount || !occurredAt} onClick={submit}>Registrar hecho</Button></FieldGroup></CardContent></Card>
  <Card><CardHeader><CardTitle>Eventos inmutables</CardTitle><CardDescription>Revertir añade una contrapartida; no reescribe el original.</CardDescription></CardHeader><CardContent>{!ledger.data?.events.length ? <Empty heading="Sin eventos" description="Todavía no hay movimientos." /> : <Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Tipo</TableHead><TableHead>Importe</TableHead><TableHead>Acción</TableHead></TableRow></TableHeader><TableBody>{ledger.data.events.map((event) => <TableRow key={event.id}><TableCell>{new Date(event.occurredAt).toLocaleString("es-ES")}</TableCell><TableCell>{event.kind}</TableCell><TableCell>{money(event.amountCents,event.currency)}</TableCell><TableCell>{event.kind === "reversal" || event.reversalOfId ? "Reversión" : <Button variant="outline" size="sm" disabled={reverse.isPending} onClick={() => reverse.mutate({ leadId, eventId:event.id, occurredAt:new Date().toISOString(), idempotencyKey:crypto.randomUUID(), note:"Reversión manual desde Verdad económica" })}>Revertir</Button>}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></>}</div>;
}
