// Explicit allowlist: no integration suites, live database access, or provider calls.
export const safeEnv = {
  DATABASE_URL: "postgresql://verification:verification@127.0.0.1:1/crm_verification",
  BETTER_AUTH_SECRET: "verification-only-secret-32-characters-minimum",
  BETTER_AUTH_URL: "http://127.0.0.1:3001",
  CORS_ORIGIN: "http://127.0.0.1:3001",
  OPENAI_API_KEY: "test-openai-api-key",
  WHATSAPP_DELIVERY_PROVIDER: "disabled",
  COMPETITOR_AD_LIBRARY_PROVIDER: "disabled",
  WHATSAPP_META_ACCESS_TOKEN: "",
  WHATSAPP_META_PHONE_NUMBER_ID: "",
  WHATSAPP_META_GRAPH_API_VERSION: "",
  COMPETITOR_AD_META_ACCESS_TOKEN: "",
  COMPETITOR_AD_META_GRAPH_API_VERSION: "",
  COMPETITOR_AD_SYNC_SECRET: "",
  GOOGLE_WORKSPACE_SERVICE_ACCOUNT_EMAIL: "",
  GOOGLE_WORKSPACE_PRIVATE_KEY: "",
  GOOGLE_WORKSPACE_DELEGATED_USER_EMAIL: "",
  GOOGLE_WORKSPACE_CALENDAR_ID: "",
  GOOGLE_WORKSPACE_SHARED_DRIVE_ID: "",
  CLOSER_MEET_SYNC_SECRET: "",
};

const apiTests = [
  "src/account-access-boundary.test.ts",
  "src/admin-export/archive.test.ts",
  "src/admin-export/authority.test.ts",
  "src/alerts/services/alert-access.test.ts",
  "src/calendar/calendar-input.test.ts",
  "src/call-feedback/call-feedback.test.ts",
  "src/closer-meet/madrid-date-time.test.ts",
  "src/closer-meet/recording-sync.test.ts",
  "src/closer-meet/service.test.ts",
  "src/closer-meet/transcript-crypto.test.ts",
  "src/closer-meet/transcript-service.test.ts",
  "src/commercial-coaching/domain.test.ts",
  "src/commercial-coaching/service.test.ts",
  "src/commercial-observatory/access.test.ts",
  "src/commercial-observatory/metric-explanations.test.ts",
  "src/competitor-ads/meta-client.test.ts",
  "src/competitor-ads/repository.test.ts",
  "src/competitor-ads/sync-service.test.ts",
  "src/dashboard/access.test.ts",
  "src/dashboard/conversion-funnel-range.test.ts",
  "src/dashboard/conversion-funnel.test.ts",
  "src/decision-center/domain.test.ts",
  "src/email-marketing/delivery-disabled.contract.test.ts",
  "src/email-marketing/delivery-provider.test.ts",
  "src/email-marketing/domain.test.ts",
  "src/email-marketing/preparation.test.ts",
  "src/email-marketing/service-authority-lock.test.ts",
  "src/email-marketing/service-preparation-persistence.test.ts",
  "src/google-workspace/auth.test.ts",
  "src/google-workspace/client.test.ts",
  "src/leads/duplicates/domain.test.ts",
  "src/leads/services/assign-to-caller.contract.test.ts",
  "src/leads/services/caller-assignment-marker.contract.test.ts",
  "src/leads/services/closer-answer-policy.test.ts",
  "src/leads/services/feedback-statistics.test.ts",
  "src/leads/services/has-closer-session.test.ts",
  "src/leads/services/has-unworked-lead.test.ts",
  "src/leads/services/personal-statistics.test.ts",
  "src/navigation-visibility.test.ts",
  "src/permissions.test.ts",
  "src/profitability/analysis.test.ts",
  "src/receivables/domain.test.ts",
  "src/routers/closer-meet-sync.test.ts",
  "src/routers/competitor-ads.test.ts",
  "src/routers/dashboard-access.test.ts",
  "src/routers/email-marketing.test.ts",
  "src/routers/leads.duplicates-access.test.ts",
  "src/routers/messages.test.ts",
  "src/routers/observatory-access.test.ts",
  "src/routers/password-recovery.test.ts",
  "src/routers/personal-feedback-access.test.ts",
  "src/routers/suggestions.test.ts",
  "src/routers/team-presence.test.ts",
  "src/routers/user-role.test.ts",
  "src/routers/whatsapp-outbox.contract.test.ts",
  "src/scheduling/time-slot.test.ts",
  "src/suggestions/domain.test.ts",
  "src/team-presence/domain.test.ts",
  "src/team-presence/repository.contract.test.ts",
  "src/team-presence/service.test.ts",
  "src/users/services/user-access-lifecycle.contract.test.ts",
  "src/whatsapp/delivery-provider.test.ts",
  "src/whatsapp/domain.test.ts",
  "src/whatsapp/draft.test.ts",
  "src/whatsapp/service-authority-lock.test.ts",
];

const dbTests = [
  "src/import/lead-csv-import.test.ts",
  "src/lead-identity.test.ts",
  "src/migrations/0039_caller_assignment_activation.test.ts",
  "src/operations/postgres-backup.test.ts",
  "src/reconciliation/payment-import.test.ts",
  "src/schema/admin-exports.test.ts",
  "src/schema/closer-sales.payment.test.ts",
  "src/schema/commercial-coaching.test.ts",
  "src/schema/competitor-ads.test.ts",
  "src/schema/email-marketing.test.ts",
  "src/schema/google-meet.test.ts",
  "src/schema/lead-duplicates.test.ts",
  "src/schema/leads.whatsapp.test.ts",
  "src/schema/payment-reconciliation.test.ts",
  "src/schema/receivables.test.ts",
  "src/schema/suggestions.test.ts",
  "src/schema/team-presence.test.ts",
  "src/schema/user-access-lifecycle.test.ts",
  "src/schema/whatsapp-migration.test.ts",
  "src/schema/whatsapp.test.ts",
];

const uiTests = [
  "src/components/app-sidebar.test.ts",
  "src/lib/email-marketing-navigation.test.ts",
  "src/lib/navigation-policy.test.ts",
];

const webTests = [
  "src/app/api/admin/exports/route.test.ts",
  "src/app/api/call-feedback/route.test.ts",
  "src/app/api/internal/closer-meet/recording-sync/route.test.ts",
  "src/app/api/internal/competitor-ads/daily-sync/route.test.ts",
  "src/components/dashboard.visual-contract.test.ts",
  "src/features/agendas/agenda-utils.test.ts",
  "src/features/alerts/alert-labels.test.ts",
  "src/features/alerts/alert-relevance.test.ts",
  "src/features/calendar/calendar-utils.test.ts",
  "src/features/closer-sales/impagos-panel.test.tsx",
  "src/features/closer-sales/receivable-label.test.ts",
  "src/features/closer-sales/sale-payment-label.test.ts",
  "src/features/commercial-observatory/advertising-library-view.test.tsx",
  "src/features/commercial-observatory/competitor-ad-library-panel.contract.test.ts",
  "src/features/commercial-observatory/metric-explanation.test.tsx",
  "src/features/email-marketing/email-marketing-preparation.test.tsx",
  "src/features/email-marketing/email-marketing-view.test.tsx",
  "src/features/leads/closer-meet-panel.test.tsx",
  "src/features/leads/lead-date-filter.test.ts",
  "src/features/leads/select-label.test.ts",
  "src/features/personal-statistics/commercial-coaching-panel.test.tsx",
  "src/features/personal-statistics/personal-statistics-integrations.contract.test.ts",
  "src/features/personal-statistics/personal-statistics-navigation.test.tsx",
  "src/features/table/mobile-lead-columns.test.tsx",
  "src/features/team-presence/team-presence.test.tsx",
  "src/features/whatsapp/whatsapp-queue.test.ts",
  "src/lib/health.test.ts",
  "src/lib/server-observability.test.ts",
];

const authTests = [
  "src/auth-http.test.ts",
  "src/password-recovery.test.ts",
  "src/role-policy.test.ts",
];

const envTests = [
  "src/server.test.ts",
];

const rootTests = [
  "scripts/local-data-backup.test.mjs",
];

export const safeTestGroups = [
  { name: "api", cwd: "packages/api", tests: apiTests },
  { name: "db", cwd: "packages/db", tests: dbTests },
  { name: "ui", cwd: "packages/ui", tests: uiTests },
  { name: "web", cwd: "apps/web", tests: webTests },
  { name: "auth", cwd: "packages/auth", extraArgs: ["--environment", "node"], tests: authTests },
  { name: "env", cwd: "packages/env", extraArgs: ["--environment", "node"], tests: envTests },
  { name: "root", cwd: ".", extraArgs: ["--environment", "node"], tests: rootTests },
];