// Explicit allowlist: no integration suites, environment setup or live database access.
export default {
  test: {
    environment: "node",
    setupFiles: [],
    fileParallelism: false,
    include: [
      "packages/api/src/routers/personal-feedback-access.test.ts",
      "packages/api/src/routers/observatory-access.test.ts",
      "packages/api/src/dashboard/conversion-funnel-range.test.ts",
      "packages/api/src/commercial-observatory/access.test.ts",
      "packages/api/src/navigation-visibility.test.ts",
      "packages/api/src/account-access-boundary.test.ts",
      "packages/api/src/users/services/user-access-lifecycle.contract.test.ts",
      "packages/ui/src/lib/navigation-policy.test.ts",
      "packages/api/src/dashboard/conversion-funnel.test.ts",
      "apps/web/src/components/dashboard.visual-contract.test.ts",
      "packages/api/src/routers/password-recovery.test.ts",
      "packages/auth/src/password-recovery.test.ts",
      "packages/auth/src/role-policy.test.ts",
      "packages/auth/src/auth-http.test.ts",
      "packages/api/src/routers/messages.test.ts",
      "packages/api/src/routers/user-role.test.ts",
      "packages/api/src/permissions.test.ts",
      "packages/api/src/calendar/calendar-input.test.ts",
      "packages/api/src/scheduling/time-slot.test.ts",
      "packages/db/src/schema/leads.whatsapp.test.ts",
      "apps/web/src/features/leads/lead-date-filter.test.ts",
      "apps/web/src/features/leads/select-label.test.ts",
      "apps/web/src/features/alerts/alert-relevance.test.ts",
      "apps/web/src/features/calendar/calendar-utils.test.ts",
      "packages/api/src/decision-center/domain.test.ts",
      "packages/api/src/leads/services/feedback-statistics.test.ts",
      "packages/api/src/leads/services/has-closer-session.test.ts",
      "packages/api/src/leads/services/personal-statistics.test.ts",
      "packages/api/src/profitability/analysis.test.ts",
      "packages/api/src/alerts/services/alert-access.test.ts",
      "packages/api/src/leads/services/closer-answer-policy.test.ts",
      "apps/web/src/features/agendas/agenda-utils.test.ts",
      "apps/web/src/features/alerts/alert-labels.test.ts",
      "packages/db/src/schema/closer-sales.payment.test.ts",
      "apps/web/src/features/closer-sales/sale-payment-label.test.ts",
      "packages/db/src/schema/suggestions.test.ts",
      "packages/api/src/suggestions/domain.test.ts",
      "packages/api/src/routers/suggestions.test.ts",
      "packages/api/src/call-feedback/call-feedback.test.ts",
      "apps/web/src/app/api/call-feedback/route.test.ts",
      "apps/web/src/features/table/mobile-lead-columns.test.tsx",
      "packages/api/src/leads/services/has-unworked-lead.test.ts",
      "packages/api/src/leads/services/assign-to-caller.contract.test.ts",
      "packages/api/src/leads/services/caller-assignment-marker.contract.test.ts",
      "packages/db/src/migrations/0039_caller_assignment_activation.test.ts",
      "packages/db/src/schema/user-access-lifecycle.test.ts",
    ],
  },
};
