import {afterEach,beforeEach,describe,it,expect,vi} from "vitest";import {cleanup,render,screen,waitFor,act} from "@testing-library/react";import {renderToString} from "react-dom/server";import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
const mocks=vi.hoisted(()=>({identity:"one",pending:false,accessStatus:"active",query:vi.fn()}));vi.mock("@/lib/auth-client",()=>({authClient:{useSession:()=>({data:mocks.identity?{user:{id:mocks.identity,accessStatus:mocks.accessStatus}}:null,isPending:mocks.pending,error:null,refetch:vi.fn()})}}));vi.mock("@/utils/trpc",()=>({trpc:{auth:{getMyAccess:{queryKey:()=>["getMyAccess"]}}},trpcClient:{auth:{getMyAccess:{query:mocks.query}}}}));
import {AppAccessProvider,useAppAccess} from "./app-access";import {usePermissionState} from "@crm-fran/ui/permissions";
function Probe(){const access=useAppAccess(),permission=usePermissionState();return <div>{access.status}:{permission.role?.id??"none"}</div>}
const data={role:{id:"role-admin",name:"Admin",permissions:["*"]},permissions:["*"],navigation:{configured:false,roleIdsByModule:{}}};
afterEach(cleanup);beforeEach(()=>{mocks.identity="one";mocks.pending=false;mocks.accessStatus="active";vi.clearAllMocks()});
describe("complete access bootstrap",()=>{
 it("waits for complete access and isolates identities",async()=>{let resolve!: (v:typeof data)=>void;mocks.query.mockImplementationOnce(()=>new Promise(r=>{resolve=r}));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const view=render(<QueryClientProvider client={client}><AppAccessProvider><Probe/></AppAccessProvider></QueryClientProvider>);expect(screen.getByText("loading:none")).toBeTruthy();await act(async()=>resolve(data));await screen.findByText("ready:role-admin");client.setQueryData(["private-admin-data"],{secret:"prior-user-data"});mocks.identity="two";mocks.query.mockImplementation(()=>new Promise(()=>{}));view.rerender(<QueryClientProvider client={client}><AppAccessProvider><Probe/></AppAccessProvider></QueryClientProvider>);expect(screen.getByText("loading:none")).toBeTruthy();expect(screen.queryByText("ready:role-admin")).toBeNull();expect(client.getQueryData(["private-admin-data"])).toBeUndefined();});
 it("does not load private access while signed out",()=>{mocks.identity="";render(<QueryClientProvider client={new QueryClient()}><AppAccessProvider><Probe/></AppAccessProvider></QueryClientProvider>);expect(screen.getByText("signed-out:none")).toBeTruthy();expect(mocks.query).not.toHaveBeenCalled();});
 it("server-renders a resolved signed-out state instead of an indefinite bootstrap placeholder",()=>{mocks.identity="";const html=renderToString(<QueryClientProvider client={new QueryClient()}><AppAccessProvider><Probe/></AppAccessProvider></QueryClientProvider>);expect(html).toContain("signed-out");expect(html).toContain("none");expect(html).not.toContain("Cargando acceso");});
 it.each([["pending","pending"],["disabled","disabled"]])("fails closed with an actionable %s account state",(accessStatus,expected)=>{mocks.accessStatus=accessStatus;render(<QueryClientProvider client={new QueryClient()}><AppAccessProvider><Probe/></AppAccessProvider></QueryClientProvider>);expect(screen.getByText(`${expected}:none`)).toBeTruthy();expect(mocks.query).not.toHaveBeenCalled();});
 it("fails closed on bootstrap errors",async()=>{mocks.query.mockRejectedValue(new Error("offline"));render(<QueryClientProvider client={new QueryClient()}><AppAccessProvider><Probe/></AppAccessProvider></QueryClientProvider>);await waitFor(()=>expect(screen.getByText("error:none")).toBeTruthy());});
});
