import { describe,expect,it } from "vitest";
import { buildEconomicScore, buildMicrosegments, calibrateEvidenceSnapshots, findTwins, parseEvidenceSnapshot, type EvidenceCase } from "./domain";
import { parseConfirmedFacts } from "./facts";
const facts=parseConfirmedFacts([{questionKey:"primaryProfile",answer:"parado_desempleado"},{questionKey:"motivationAngles",answer:'["financial_stability"]'}]);
const base=(id:string,sold=false):EvidenceCase=>({epochId:`${id}:epoch`,leadId:id,assignmentAt:new Date("2025-01-01"),assignmentEndedAt:null,featureCutoffAt:new Date("2025-02-01"),callerId:null,closerId:null,facts,acquisition:{source:"Meta",campaign:"A",ad:null,creative:null,acquisitionAngle:null},sold,financialEvents:[]});
describe("commercial evidence",()=>{
 it("rejects future asOf and keeps missing ledger truth unknown",()=>{expect(()=>buildEconomicScore({target:base("t"),cohort:[],asOf:new Date("2999-01-01"),currency:"EUR"})).toThrow();expect(buildEconomicScore({target:base("t"),cohort:Array.from({length:10},(_,i)=>base(String(i),i<5)),asOf:new Date("2026-01-01"),currency:"EUR"}).expectedMarginCents).toBeNull();});
 it("uses reversal-aware selected-currency monetary truth",()=>{const sold=base("sold",true);sold.financialEvents=[{id:"p",kind:"payment_received",amountCents:10000,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")},{id:"c",kind:"cost",amountCents:2000,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")},{id:"r",kind:"reversal",amountCents:2000,currency:"EUR",reversalOfId:"c",occurredAt:new Date("2025-02-02")}];const score=buildEconomicScore({target:base("t"),cohort:Array.from({length:10},(_,i)=>i===0?sold:base(String(i))),asOf:new Date("2026-01-01"),currency:"EUR"});expect(score.realizedMarginBeforeAdsMedianCents).toBe(10000);});
 it("deidentifies twins and selection is invariant to outcome",()=>{const first=findTwins({target:base("target"),cohort:[base("a",false),base("b",true)],asOf:new Date("2026-01-01"),currency:"EUR",referenceSecret:"private-test-secret"});const second=findTwins({target:base("target"),cohort:[base("a",true),base("b",false)],asOf:new Date("2026-01-01"),currency:"EUR",referenceSecret:"private-test-secret"});expect(first.items.map(x=>x.caseRef)).toEqual(second.items.map(x=>x.caseRef));expect(first.items[0]).not.toHaveProperty("leadId");});
 it("suppresses microsegments with small complements",()=>{const cohort=Array.from({length:35},(_,i)=>base(String(i),i<10));expect(buildMicrosegments({cohort,asOf:new Date("2026-01-01"),currency:"EUR"})).toHaveLength(0);});
 it("calibrates only mature server-shaped snapshots",()=>{const snapshot=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01T00:00:00.000Z",target:"sale",probabilityBps:5000,expectedMarginCents:null,currency:"EUR",fallback:"global",sample:30,confidence:"medium",features:{source:"Meta"}});expect(snapshot).not.toBeNull();expect(parseEvidenceSnapshot({...snapshot,probabilityBps:20000})).toBeNull();const result=calibrateEvidenceSnapshots({asOf:new Date("2026-02-01"),rows:[{snapshot:snapshot!,shownAt:new Date("2026-01-01"),soldAt:new Date("2026-01-10")},{snapshot:snapshot!,shownAt:new Date("2026-01-20"),soldAt:null}]});expect(result.sample).toBe(1);expect(result.brier).toBe(0.25);});
 it("excludes pre-shown sales and missing economic probabilities from calibration",()=>{const snapshot=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01T00:00:00.000Z",target:"sale",probabilityBps:5000,expectedMarginCents:null,currency:"EUR",fallback:"global",sample:30,confidence:"medium",features:{}})!;const missing=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01T00:00:00.000Z",target:"sale",probabilityBps:null,expectedMarginCents:null,currency:null,fallback:"unavailable",sample:0,confidence:"insufficient",features:{},status:"economic_truth_missing"})!;const result=calibrateEvidenceSnapshots({asOf:new Date("2026-03-01"),rows:[{snapshot,shownAt:new Date("2026-01-01"),soldAt:new Date("2025-12-31")},{snapshot:missing,shownAt:new Date("2026-01-01"),soldAt:new Date("2026-01-10")}]});expect(result.sample).toBe(1);expect(result.brier).toBe(0.25);});
 it("uses recursive child-to-parent shrinkage and a real cohort margin scale",()=>{const cohort=Array.from({length:50},(_,i)=>{const item=base(String(i),i<20);item.acquisition.campaign=i<12?"A":"B";if(item.sold)item.financialEvents=[{id:`p-${i}`,kind:"payment_received",amountCents:10_000+i*100,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")}];return item;});const score=buildEconomicScore({target:base("target"),cohort,asOf:new Date("2026-01-01"),currency:"EUR"});expect(score.hierarchy.length).toBeGreaterThan(1);expect(score.hierarchy[0]?.parentProbabilityBps).toBe(score.hierarchy[1]?.probabilityBps);expect(score.score0To100).toBeGreaterThanOrEqual(0);expect(score.score0To100).toBeLessThanOrEqual(100);expect(score.marginScaleCents.p10).not.toBeNull();expect(score.marginScaleCents.p90).not.toBeNull();});
 it("reports calibration intervals, weekly history and policy/fallback breakdown",()=>{const snapshot=parseEvidenceSnapshot({policyVersion:"v1",asOf:"2025-01-01T00:00:00.000Z",target:"sale",probabilityBps:5000,expectedMarginCents:null,currency:"EUR",fallback:"source",sample:30,confidence:"medium",features:{}})!;const result=calibrateEvidenceSnapshots({asOf:new Date("2026-03-01"),rows:[{snapshot,shownAt:new Date("2026-01-01"),soldAt:new Date("2026-01-10")},{snapshot,shownAt:new Date("2026-01-08"),soldAt:null}]});expect(result.sample).toBe(2);expect(result.bins.find(bin=>bin.sample)?.actualWilsonBps).toEqual(expect.objectContaining({low:expect.any(Number),high:expect.any(Number)}));expect(result.weekly).toHaveLength(2);expect(result.byPolicy).toEqual([expect.objectContaining({key:"v1",sample:2})]);expect(result.byFallback).toEqual([expect.objectContaining({key:"source",sample:2})]);});
 it("rejects malformed or incoherent evidence snapshots",()=>{const valid={policyVersion:"v1",asOf:"2025-01-01T00:00:00.000Z",target:"sale",probabilityBps:5000,expectedMarginCents:100,currency:"EUR",fallback:"source",sample:3,confidence:"medium",features:{source:"Meta"}};for(const invalid of [null,{...valid,asOf:"not-a-date"},{...valid,sample:-1},{...valid,sample:1.5},{...valid,features:null},{...valid,expectedMarginCents:100,currency:null},{...valid,probabilityBps:null,expectedMarginCents:100}])expect(parseEvidenceSnapshot(invalid)).toBeNull();});
 it("enforces the complete scored and missing discriminants",()=>{const scored={policyVersion:"v1",asOf:"2025-01-01T00:00:00.000Z",target:"sale",probabilityBps:5000,expectedMarginCents:null,currency:"EUR",fallback:"global",sample:3,confidence:"low",features:{}};const missing={...scored,probabilityBps:null,expectedMarginCents:null,currency:null,fallback:"unavailable",sample:0,confidence:"insufficient",status:"economic_truth_missing"};expect(parseEvidenceSnapshot(scored)).not.toBeNull();expect(parseEvidenceSnapshot(missing)).not.toBeNull();for(const invalid of [{...scored,asOf:"2025-01-01"},{...scored,confidence:"insufficient"},{...scored,confidence:"unknown"},{...scored,fallback:"unavailable"},{...scored,status:"economic_truth_missing"},{...missing,sample:1},{...missing,confidence:"low"},{...missing,fallback:"global"},{...missing,currency:"EUR"},{...missing,status:undefined}])expect(parseEvidenceSnapshot(invalid)).toBeNull();});
 it("uses only unique comparable and symmetrically money-mature epochs for the margin scale",()=>{const target=base("target");const comparable=Array.from({length:12},(_,i)=>{const item=base(`a-${i}`,i<8);if(item.sold)item.financialEvents=[{id:`eur-${i}`,kind:"payment_received",amountCents:10_000+i*100,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")}];return item;});const duplicate={...comparable[0]!,epochId:"duplicate-epoch",sold:false};const outlier=base("outlier",true);outlier.acquisition.campaign="B";outlier.financialEvents=[{id:"huge",kind:"payment_received",amountCents:1_000_000,currency:"EUR",reversalOfId:null,occurredAt:new Date("2025-02-01")}];const midAge=base("mid-age",false);midAge.assignmentAt=new Date("2025-11-01");const score=buildEconomicScore({target,cohort:[...comparable,duplicate,outlier,midAge],asOf:new Date("2026-01-01"),currency:"EUR"});expect(score.denominator).toBe(13);expect(score.marginScaleSample).toBe(12);expect(score.marginScaleCents.p90).toBeLessThan(20_000);});
 it("fails closed when the private twin reference secret is absent",()=>{expect(findTwins({target:base("target"),cohort:[base("a")],asOf:new Date("2026-01-01"),currency:"EUR",referenceSecret:""})).toEqual({status:"reference_secret_missing",items:[]});});
});
