import { TRPCError } from "@trpc/server";
import { and, db, eq, lte } from "@crm-fran/db";
import { leadActivityEvents, leadFinancialEvents, leads } from "@crm-fran/db/schema/index";
import { env } from "@crm-fran/env/server";
import { buildAsOfCases } from "./cohort";
import { buildEconomicScore, buildMicrosegments, calibrateEvidenceSnapshots, findTwins, parseEvidenceSnapshot, COMMERCIAL_EVIDENCE_POLICY_VERSION, type EvidenceCase, type EvidenceSnapshot } from "./domain";

export async function loadCommercialEvidenceData(asOf:Date){
 const [leadRows,activityRows,financialRows]=await Promise.all([
  db.select({id:leads.id,type:leads.type,createdAt:leads.createdAt,callerId:leads.callerId,closerId:leads.closerId,name:leads.name}).from(leads).where(lte(leads.createdAt,asOf)),
  db.select({id:leadActivityEvents.id,leadId:leadActivityEvents.leadId,kind:leadActivityEvents.kind,occurredAt:leadActivityEvents.occurredAt,description:leadActivityEvents.description,metadata:leadActivityEvents.metadata}).from(leadActivityEvents).where(lte(leadActivityEvents.occurredAt,asOf)),
  db.select({id:leadFinancialEvents.id,leadId:leadFinancialEvents.leadId,kind:leadFinancialEvents.kind,amountCents:leadFinancialEvents.amountCents,currency:leadFinancialEvents.currency,reversalOfId:leadFinancialEvents.reversalOfId,occurredAt:leadFinancialEvents.occurredAt}).from(leadFinancialEvents).where(lte(leadFinancialEvents.occurredAt,asOf)),
 ]);
 return {leadRows,activityRows,financialRows,cases:buildAsOfCases({leads:leadRows,activities:activityRows,financial:financialRows,asOf})};
}
const latestCase=(cases:readonly EvidenceCase[],leadId:string)=>cases.filter(item=>item.leadId===leadId).sort((a,b)=>b.assignmentAt.getTime()-a.assignmentAt.getTime())[0];
export async function buildEvidenceSnapshotForLead(input:{leadId:string;asOf:Date;actionType:string}):Promise<EvidenceSnapshot>{const {cases}=await loadCommercialEvidenceData(input.asOf);const target=latestCase(cases,input.leadId);const currency=[...new Set(cases.flatMap(item=>item.financialEvents.map(event=>event.currency)))].sort()[0];if(!target||!currency)return {policyVersion:COMMERCIAL_EVIDENCE_POLICY_VERSION,asOf:input.asOf.toISOString(),target:"sale",probabilityBps:null,expectedMarginCents:null,currency:null,fallback:"unavailable",sample:0,confidence:"insufficient",features:{actionType:input.actionType},status:"economic_truth_missing"};const score=buildEconomicScore({target,cohort:cases,asOf:input.asOf,currency});return {policyVersion:score.policyVersion,asOf:input.asOf.toISOString(),target:"sale",probabilityBps:score.probabilityBps,expectedMarginCents:score.expectedMarginCents,currency,fallback:score.fallback,sample:score.denominator,confidence:score.confidence,features:{actionType:input.actionType,source:target.acquisition.source??"missing",profile:target.facts.primaryProfile.kind==="value"?target.facts.primaryProfile.value:"missing"}};}
export function canReadEvidenceLead(input:{actorId:string;admin:boolean;callerId:string|null;closerId:string|null}){return input.admin||input.callerId===input.actorId||input.closerId===input.actorId;}
export async function getLeadEvidence(input:{leadId:string;asOf:Date;currency:string;actorId:string;admin:boolean}){const {leadRows,cases}=await loadCommercialEvidenceData(input.asOf);const lead=leadRows.find(x=>x.id===input.leadId);if(!lead)throw new TRPCError({code:"NOT_FOUND",message:"Lead not found"});if(!canReadEvidenceLead({...input,callerId:lead.callerId,closerId:lead.closerId}))throw new TRPCError({code:"FORBIDDEN",message:"Lead is not assigned to this user"});const target=latestCase(cases,input.leadId);if(!target)throw new TRPCError({code:"NOT_FOUND",message:"No evidence epoch exists for this lead"});return {lead:{id:lead.id,name:lead.name},score:buildEconomicScore({target,cohort:cases,asOf:input.asOf,currency:input.currency}),twins:findTwins({target,cohort:cases,asOf:input.asOf,currency:input.currency,referenceSecret:env.BETTER_AUTH_SECRET,admin:input.admin})};}
export async function listEvidenceCurrencies(input:{actorId:string;admin:boolean}){const [owners,events]=await Promise.all([db.select({id:leads.id,callerId:leads.callerId,closerId:leads.closerId}).from(leads),db.select({leadId:leadFinancialEvents.leadId,currency:leadFinancialEvents.currency}).from(leadFinancialEvents)]);const allowed=new Set(owners.filter(x=>input.admin||x.callerId===input.actorId||x.closerId===input.actorId).map(x=>x.id));return [...new Set(events.filter(x=>allowed.has(x.leadId)).map(x=>x.currency))].sort();}
export async function listEvidenceLeads(input:{actorId:string;admin:boolean;query?:string}){const rows=await db.select({id:leads.id,name:leads.name,callerId:leads.callerId,closerId:leads.closerId}).from(leads);const q=input.query?.trim().toLowerCase();return rows.filter(x=>(input.admin||x.callerId===input.actorId||x.closerId===input.actorId)&&(!q||x.name.toLowerCase().includes(q))).slice(0,50).map(({id,name})=>({id,name}));}
export async function getMicrosegments(asOf:Date,currency:string){const {cases}=await loadCommercialEvidenceData(asOf);return buildMicrosegments({cohort:cases,asOf,currency});}
export function buildConfidenceReport(input:{asOf:Date;cases:readonly EvidenceCase[];shown:readonly {leadId:string;occurredAt:Date;metadata:Record<string,unknown>}[]}){const maturedShown=input.shown.filter(row=>input.asOf.getTime()-row.occurredAt.getTime()>=30*86_400_000);const valid=maturedShown.flatMap(row=>{const snapshot=parseEvidenceSnapshot(row.metadata.evidenceSnapshot);if(!snapshot)return[];const soldAt=input.cases.filter(item=>item.leadId===row.leadId).flatMap(item=>item.saleTimestamps??[]).filter(date=>date>row.occurredAt).sort((a,b)=>a.getTime()-b.getTime())[0]??null;return[{snapshot,shownAt:row.occurredAt,soldAt}]});const calibration=calibrateEvidenceSnapshots({rows:valid,asOf:input.asOf});const missingEconomic=valid.filter(row=>row.snapshot.probabilityBps===null).length;return {policyVersion:COMMERCIAL_EVIDENCE_POLICY_VERSION,coverage:{maturedShown:maturedShown.length,calibrated:calibration.sample,rateBps:maturedShown.length?Math.round(calibration.sample/maturedShown.length*10_000):null},legacyExcluded:maturedShown.length-valid.length,missingEconomic,brier:calibration.brier,ece:calibration.ece,bins:calibration.bins,weekly:calibration.weekly,byPolicy:calibration.byPolicy,byFallback:calibration.byFallback,suggestedChanges:[],mode:"shadow-only" as const};}
export async function getConfidenceCentre(asOf:Date){const {cases}=await loadCommercialEvidenceData(asOf);const shown=await db.select({leadId:leadActivityEvents.leadId,occurredAt:leadActivityEvents.occurredAt,metadata:leadActivityEvents.metadata}).from(leadActivityEvents).where(and(lte(leadActivityEvents.occurredAt,asOf),eq(leadActivityEvents.kind,"recommendation_shown")));return buildConfidenceReport({asOf,cases,shown});}
