const LABELS: Readonly<Record<string, string>> = {
  observational_gap: "Brecha observacional",
  approved_experiment: "Experimento aprobado",
  observational: "Observacional",
  experimental: "Respaldada por experimento",
  experiment_supported: "Respaldada por experimento",
  insufficient: "Evidencia insuficiente",
  available: "Disponible",
  insufficient_evidence: "Evidencia insuficiente",
  currency_required: "Moneda necesaria",
  not_comparable: "No comparable",
  anomaly: "Anomalía",
  within_expected_range: "Dentro del rango esperado",
  high: "Alto",
  medium: "Medio",
  low: "Bajo",
  draft: "Borrador",
  approved: "Aprobada",
  rejected: "Rechazada",
  published: "Publicada",
  archived: "Archivada",
  manual: "Manual",
  learned: "Aprendida",
  rollback: "Restauración",
  observed: "Observado",
  introduced: "Introducido",
  policy_default: "Valor de política",
  source: "Fuente",
  campaign: "Campaña",
  caller: "Caller",
  closer: "Closer",
  profile: "Perfil",
  subprofile: "Subperfil",
  type: "Tipo",
  volume: "Volumen",
  conversion: "Conversión",
  sales: "Ventas",
  margin: "Margen",
  reaction: "Reacción",
  delta_margin: "Variación de margen",
  delta_sales: "Variación de ventas",
  volume_contribution: "Contribución del volumen",
  conversion_contribution: "Contribución de la conversión",
  top_1_share: "Peso del grupo principal",
  actual_probability: "Probabilidad observada",
  realized_margin: "Margen realizado",
  count: "Conteo",
  ratio: "Proporción",
  cents: "Importe",
  basis_points: "Porcentaje",
  downside: "Escenario desfavorable",
  base: "Escenario base",
  upside: "Escenario favorable",
  none: "Sin bonus",
  goal: "Objetivo",
  stretch: "Objetivo ampliado",
  motivation: "Motivación",
  objection: "Objeción",
  acquisitionAngle: "Ángulo de adquisición",
  missing: "Sin información",
  unavailable: "No disponible",
  "profile+subprofile+source+campaign": "Perfil, subperfil, fuente y campaña",
  "profile+source+campaign": "Perfil, fuente y campaña",
  "profile+source": "Perfil y fuente",
  global: "Global",
};

export function commercialUiLabel(value: string) {
  const exact = LABELS[value];
  if (exact) return exact;
  const words = value.replaceAll("_", " ").trim();
  return words ? words[0]!.toLocaleUpperCase("es-ES") + words.slice(1) : value;
}
